#-------------------------------------------------
# Project
#-------------------------------------------------
SRC_PATH		:= .
TARGETPATH		:= $(TESTDRIVE_DIR)/bin
TARGETNAME		:= iStyle

SRCS			:= \
	$(wildcard $(SRC_PATH)/*.cpp)
	
INC				:=

CDEFS			:= -s
CFLAGS			:= -O3 -DNDEBUG

#-------------------------------------------------
# common document config
#-------------------------------------------------

BUILD_TARGET	= $(TARGET_EXE)

include $(TESTDRIVE_PROFILE)/common/include/config.mk
